package com.example.elderease;

import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.os.Bundle;
import android.telephony.SmsManager;
import android.view.View;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.cardview.widget.CardView;

import com.example.elderease.medicine.MedicineActivity;
import android.Manifest;

public class homeScreen extends AppCompatActivity  {

    CardView medRem;
    CardView magnify;
    Button sos;
    private DBHelper db;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_home_screen);

//        int permissionCheck = Context.checkSelfPermission(getActivity(),
//                Manifest.permission.CAMERA);
//        if (permissionCheck== PackageManager.PERMISSION_DENIED) {
//            requestPermissions(new String[]{Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE}, REQUEST_WRITE_STORAGE);
//        }








        db = new DBHelper(this);
        Cursor cursor = db.getData();



        magnify = findViewById(R.id.magnify);

        magnify.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(homeScreen.this,magnifier.class);
                startActivity(intent);
            }
        });

        medRem = findViewById(R.id.medRem);

        medRem.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(homeScreen.this, MedicineActivity.class);
                startActivity(intent);
            }

        });

        sos = findViewById(R.id.sos);

        sos.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(homeScreen.this, sos.class);
                startActivity(intent);
            }
        });

        sos.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View view) {
                if (cursor.getCount() !=0){
                    cursor.moveToFirst();
                    SmsManager sms = SmsManager.getDefault();
                    LocationManager lm = (LocationManager) getSystemService(Context.LOCATION_SERVICE);
                    Location location = lm.getLastKnownLocation(LocationManager.PASSIVE_PROVIDER);
                    String Location = "https://www.google.co.in/maps/@"+location.getLatitude()+","+ location.getLongitude() + ",15z";

                    String preMessage = "This is an autogenerated message via Elder Ease app SOS help function : " + cursor.getString(3)+ "\n"
                            + "  " + Location;

                    sms.sendTextMessage((cursor.getString(1)),null,preMessage,null,null);
                    sms.sendTextMessage((cursor.getString(2)),null,preMessage,null,null);

                    Toast.makeText(getApplicationContext(),"Emergency message sent successfully",
                            Toast.LENGTH_LONG).show();
                    System.out.println("Messages sent");

                }
                return true;
            }
        });






    }


}